"""empty message

Revision ID: 11886d1e70b0
Revises: 
Create Date: 2020-10-15 17:24:24.990994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11886d1e70b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_m_user_id'), 'm_user', ['id'], unique=True)
    op.create_index(op.f('ix_m_user_username'), 'm_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_m_user_username'), table_name='m_user')
    op.drop_index(op.f('ix_m_user_id'), table_name='m_user')
    op.drop_table('m_user')
    # ### end Alembic commands ###
