"""empty message

Revision ID: 41dff3237c34
Revises: 
Create Date: 2020-10-23 18:35:46.285520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41dff3237c34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_m_user_id'), 'm_user', ['id'], unique=True)
    op.create_index(op.f('ix_m_user_username'), 'm_user', ['username'], unique=True)
    op.create_table('t_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=False),
    sa.Column('contents', sa.VARCHAR(length=500), nullable=False),
    sa.Column('japanese_level', sa.VARCHAR(length=50), nullable=False),
    sa.Column('published_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['m_user.id'], ),
    sa.PrimaryKeyConstraint('id', 'title', 'contents')
    )
    op.create_index(op.f('ix_t_topics_contents'), 't_topics', ['contents'], unique=False)
    op.create_index(op.f('ix_t_topics_id'), 't_topics', ['id'], unique=True)
    op.create_index(op.f('ix_t_topics_title'), 't_topics', ['title'], unique=False)
    op.create_table('m_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=False),
    sa.Column('contents', sa.VARCHAR(length=500), nullable=False),
    sa.Column('published_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['m_user.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['t_topics.id'], ),
    sa.PrimaryKeyConstraint('id', 'title', 'contents')
    )
    op.create_index(op.f('ix_m_answer_id'), 'm_answer', ['id'], unique=True)
    op.create_table('m_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('up_votes', sa.Integer(), nullable=True),
    sa.Column('down_votes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['m_answer.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['m_user.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['t_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_m_votes_id'), 'm_votes', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_m_votes_id'), table_name='m_votes')
    op.drop_table('m_votes')
    op.drop_index(op.f('ix_m_answer_id'), table_name='m_answer')
    op.drop_table('m_answer')
    op.drop_index(op.f('ix_t_topics_title'), table_name='t_topics')
    op.drop_index(op.f('ix_t_topics_id'), table_name='t_topics')
    op.drop_index(op.f('ix_t_topics_contents'), table_name='t_topics')
    op.drop_table('t_topics')
    op.drop_index(op.f('ix_m_user_username'), table_name='m_user')
    op.drop_index(op.f('ix_m_user_id'), table_name='m_user')
    op.drop_table('m_user')
    # ### end Alembic commands ###
